// @routes-hash 8fcf006c33d4705a20117ed4d821cc8d
import { Express } from "express";

import route1 from "./routes/agents/clearMemory";
import route2 from "./routes/agents/getMemory";
import route3 from "./routes/artStyle/addArtStyle";
import route4 from "./routes/artStyle/editArtStyle";
import route5 from "./routes/artStyle/extractStylePrompt";
import route6 from "./routes/artStyle/getArtStyle";
import route7 from "./routes/assets/addAssets";
import route8 from "./routes/assets/batchDelete";
import route9 from "./routes/assets/batchGenerationData";
import route10 from "./routes/assets/delAssets";
import route11 from "./routes/assets/getAssetsApi";
import route12 from "./routes/assets/getImage";
import route13 from "./routes/assets/getMaterialData";
import route14 from "./routes/assets/pollingImageAssets";
import route15 from "./routes/assets/pollingPromptAssets";
import route16 from "./routes/assets/saveAssets";
import route17 from "./routes/assets/updateAssets";
import route18 from "./routes/assets/uploadClip";
import route19 from "./routes/assetsGenerate/batchGenerateImageAssets";
import route20 from "./routes/assetsGenerate/batchPolishAssetsPrompt";
import route21 from "./routes/assetsGenerate/generateAssets";
import route22 from "./routes/assetsGenerate/polishAssetsPrompt";
import route23 from "./routes/cornerScape/getAllAssets";
import route24 from "./routes/general/generalStatistics";
import route25 from "./routes/general/getSingleProject";
import route26 from "./routes/general/updateProject";
import route27 from "./routes/login/login";
import route28 from "./routes/migrate/migrateData";
import route29 from "./routes/modelSelect/getModelDetail";
import route30 from "./routes/modelSelect/getModelList";
import route31 from "./routes/novel/addNovel";
import route32 from "./routes/novel/batchDeleteNovel";
import route33 from "./routes/novel/delNovel";
import route34 from "./routes/novel/event/batchDeleteEvent";
import route35 from "./routes/novel/event/deletEvent";
import route36 from "./routes/novel/event/generateEvents";
import route37 from "./routes/novel/event/getEvent";
import route38 from "./routes/novel/getNovel";
import route39 from "./routes/novel/getNovelData";
import route40 from "./routes/novel/getNovelEventState";
import route41 from "./routes/novel/getNovelIndex";
import route42 from "./routes/novel/updateNovel";
import route43 from "./routes/other/deleteAllData";
import route44 from "./routes/other/getVersion";
import route45 from "./routes/production/assets/batchGenerateAssetsImage";
import route46 from "./routes/production/assets/getAssetsData";
import route47 from "./routes/production/assets/pollingImage";
import route48 from "./routes/production/assets/updateAssetsUrl";
import route49 from "./routes/production/editImage/generateFlowImage";
import route50 from "./routes/production/editImage/getImageDefaultModle";
import route51 from "./routes/production/editImage/getImageFlow";
import route52 from "./routes/production/editImage/saveImageFlow";
import route53 from "./routes/production/editImage/updateImageFlow";
import route54 from "./routes/production/exportImage";
import route55 from "./routes/production/getFlowData";
import route56 from "./routes/production/getProductionData";
import route57 from "./routes/production/getStoryboardData";
import route58 from "./routes/production/saveFlowData";
import route59 from "./routes/production/storyboard/addStoryboard";
import route60 from "./routes/production/storyboard/batchAddStoryboardInfo";
import route61 from "./routes/production/storyboard/batchGenerateImage";
import route62 from "./routes/production/storyboard/downPreviewImage";
import route63 from "./routes/production/storyboard/editStoryboardInfo";
import route64 from "./routes/production/storyboard/getStoryboardData";
import route65 from "./routes/production/storyboard/pollingImage";
import route66 from "./routes/production/storyboard/previewImage";
import route67 from "./routes/production/storyboard/removeFrame";
import route68 from "./routes/production/storyboard/updateStoryboardUrl";
import route69 from "./routes/production/workbench/addTrack";
import route70 from "./routes/production/workbench/deleteTrack";
import route71 from "./routes/production/workbench/delVideo";
import route72 from "./routes/production/workbench/generateVideo";
import route73 from "./routes/production/workbench/generateVideoPrompt";
import route74 from "./routes/production/workbench/getGenerateData";
import route75 from "./routes/production/workbench/getVideoList";
import route76 from "./routes/production/workbench/getVideoModelDetail";
import route77 from "./routes/production/workbench/selectVideo";
import route78 from "./routes/project/addDirectorManual";
import route79 from "./routes/project/addProject";
import route80 from "./routes/project/addVisualManual";
import route81 from "./routes/project/deleteDirectorManual";
import route82 from "./routes/project/deleteVisualManual";
import route83 from "./routes/project/delProject";
import route84 from "./routes/project/editDirectorlManual";
import route85 from "./routes/project/editProject";
import route86 from "./routes/project/editVisualManual";
import route87 from "./routes/project/getProject";
import route88 from "./routes/project/getVisualManual";
import route89 from "./routes/project/queryDirectorManual";
import route90 from "./routes/project/visualManual";
import route91 from "./routes/script/addScript";
import route92 from "./routes/script/delScript";
import route93 from "./routes/script/exportScript";
import route94 from "./routes/script/extractAssets";
import route95 from "./routes/script/getScrptApi";
import route96 from "./routes/script/pollScriptAssets";
import route97 from "./routes/script/updateScript";
import route98 from "./routes/scriptAgent/getPlanData";
import route99 from "./routes/scriptAgent/setPlanData";
import route100 from "./routes/scriptAgent/updateData";
import route101 from "./routes/setting/about/checkUpdate";
import route102 from "./routes/setting/about/downloadApp";
import route103 from "./routes/setting/agentDeploy/agentSetKey";
import route104 from "./routes/setting/agentDeploy/deployAgentModel";
import route105 from "./routes/setting/agentDeploy/getAgentDeploy";
import route106 from "./routes/setting/dbConfig/clearData";
import route107 from "./routes/setting/dev/getSwitchAiDevTool";
import route108 from "./routes/setting/dev/updateSwitchAiDevTool";
import route109 from "./routes/setting/fileManagement/openFolder";
import route110 from "./routes/setting/getTextModel";
import route111 from "./routes/setting/loginConfig/getUser";
import route112 from "./routes/setting/loginConfig/updateUserPwd";
import route113 from "./routes/setting/memoryConfig/delAllMemory";
import route114 from "./routes/setting/memoryConfig/getMemory";
import route115 from "./routes/setting/memoryConfig/sureMemory";
import route116 from "./routes/setting/promptManage/getPrompt";
import route117 from "./routes/setting/promptManage/updatePrompt";
import route118 from "./routes/setting/skillManagement/getSkillContent";
import route119 from "./routes/setting/skillManagement/getSkillList";
import route120 from "./routes/setting/skillManagement/saveSkillContent";
import route121 from "./routes/setting/vendorConfig/addVendor";
import route122 from "./routes/setting/vendorConfig/deleteVendor";
import route123 from "./routes/setting/vendorConfig/enableVendor";
import route124 from "./routes/setting/vendorConfig/getCodeByLink";
import route125 from "./routes/setting/vendorConfig/getVendorList";
import route126 from "./routes/setting/vendorConfig/modelTest";
import route127 from "./routes/setting/vendorConfig/updateCode";
import route128 from "./routes/setting/vendorConfig/updateVendor";
import route129 from "./routes/task/getProject";
import route130 from "./routes/task/getTaskApi";
import route131 from "./routes/task/getTaskCategories";
import route132 from "./routes/task/taskDetails";
import route133 from "./routes/test/test";

export default async (app: Express) => {
  app.use("/api/agents/clearMemory", route1);
  app.use("/api/agents/getMemory", route2);
  app.use("/api/artStyle/addArtStyle", route3);
  app.use("/api/artStyle/editArtStyle", route4);
  app.use("/api/artStyle/extractStylePrompt", route5);
  app.use("/api/artStyle/getArtStyle", route6);
  app.use("/api/assets/addAssets", route7);
  app.use("/api/assets/batchDelete", route8);
  app.use("/api/assets/batchGenerationData", route9);
  app.use("/api/assets/delAssets", route10);
  app.use("/api/assets/getAssetsApi", route11);
  app.use("/api/assets/getImage", route12);
  app.use("/api/assets/getMaterialData", route13);
  app.use("/api/assets/pollingImageAssets", route14);
  app.use("/api/assets/pollingPromptAssets", route15);
  app.use("/api/assets/saveAssets", route16);
  app.use("/api/assets/updateAssets", route17);
  app.use("/api/assets/uploadClip", route18);
  app.use("/api/assetsGenerate/batchGenerateImageAssets", route19);
  app.use("/api/assetsGenerate/batchPolishAssetsPrompt", route20);
  app.use("/api/assetsGenerate/generateAssets", route21);
  app.use("/api/assetsGenerate/polishAssetsPrompt", route22);
  app.use("/api/cornerScape/getAllAssets", route23);
  app.use("/api/general/generalStatistics", route24);
  app.use("/api/general/getSingleProject", route25);
  app.use("/api/general/updateProject", route26);
  app.use("/api/login/login", route27);
  app.use("/api/migrate/migrateData", route28);
  app.use("/api/modelSelect/getModelDetail", route29);
  app.use("/api/modelSelect/getModelList", route30);
  app.use("/api/novel/addNovel", route31);
  app.use("/api/novel/batchDeleteNovel", route32);
  app.use("/api/novel/delNovel", route33);
  app.use("/api/novel/event/batchDeleteEvent", route34);
  app.use("/api/novel/event/deletEvent", route35);
  app.use("/api/novel/event/generateEvents", route36);
  app.use("/api/novel/event/getEvent", route37);
  app.use("/api/novel/getNovel", route38);
  app.use("/api/novel/getNovelData", route39);
  app.use("/api/novel/getNovelEventState", route40);
  app.use("/api/novel/getNovelIndex", route41);
  app.use("/api/novel/updateNovel", route42);
  app.use("/api/other/deleteAllData", route43);
  app.use("/api/other/getVersion", route44);
  app.use("/api/production/assets/batchGenerateAssetsImage", route45);
  app.use("/api/production/assets/getAssetsData", route46);
  app.use("/api/production/assets/pollingImage", route47);
  app.use("/api/production/assets/updateAssetsUrl", route48);
  app.use("/api/production/editImage/generateFlowImage", route49);
  app.use("/api/production/editImage/getImageDefaultModle", route50);
  app.use("/api/production/editImage/getImageFlow", route51);
  app.use("/api/production/editImage/saveImageFlow", route52);
  app.use("/api/production/editImage/updateImageFlow", route53);
  app.use("/api/production/exportImage", route54);
  app.use("/api/production/getFlowData", route55);
  app.use("/api/production/getProductionData", route56);
  app.use("/api/production/getStoryboardData", route57);
  app.use("/api/production/saveFlowData", route58);
  app.use("/api/production/storyboard/addStoryboard", route59);
  app.use("/api/production/storyboard/batchAddStoryboardInfo", route60);
  app.use("/api/production/storyboard/batchGenerateImage", route61);
  app.use("/api/production/storyboard/downPreviewImage", route62);
  app.use("/api/production/storyboard/editStoryboardInfo", route63);
  app.use("/api/production/storyboard/getStoryboardData", route64);
  app.use("/api/production/storyboard/pollingImage", route65);
  app.use("/api/production/storyboard/previewImage", route66);
  app.use("/api/production/storyboard/removeFrame", route67);
  app.use("/api/production/storyboard/updateStoryboardUrl", route68);
  app.use("/api/production/workbench/addTrack", route69);
  app.use("/api/production/workbench/deleteTrack", route70);
  app.use("/api/production/workbench/delVideo", route71);
  app.use("/api/production/workbench/generateVideo", route72);
  app.use("/api/production/workbench/generateVideoPrompt", route73);
  app.use("/api/production/workbench/getGenerateData", route74);
  app.use("/api/production/workbench/getVideoList", route75);
  app.use("/api/production/workbench/getVideoModelDetail", route76);
  app.use("/api/production/workbench/selectVideo", route77);
  app.use("/api/project/addDirectorManual", route78);
  app.use("/api/project/addProject", route79);
  app.use("/api/project/addVisualManual", route80);
  app.use("/api/project/deleteDirectorManual", route81);
  app.use("/api/project/deleteVisualManual", route82);
  app.use("/api/project/delProject", route83);
  app.use("/api/project/editDirectorlManual", route84);
  app.use("/api/project/editProject", route85);
  app.use("/api/project/editVisualManual", route86);
  app.use("/api/project/getProject", route87);
  app.use("/api/project/getVisualManual", route88);
  app.use("/api/project/queryDirectorManual", route89);
  app.use("/api/project/visualManual", route90);
  app.use("/api/script/addScript", route91);
  app.use("/api/script/delScript", route92);
  app.use("/api/script/exportScript", route93);
  app.use("/api/script/extractAssets", route94);
  app.use("/api/script/getScrptApi", route95);
  app.use("/api/script/pollScriptAssets", route96);
  app.use("/api/script/updateScript", route97);
  app.use("/api/scriptAgent/getPlanData", route98);
  app.use("/api/scriptAgent/setPlanData", route99);
  app.use("/api/scriptAgent/updateData", route100);
  app.use("/api/setting/about/checkUpdate", route101);
  app.use("/api/setting/about/downloadApp", route102);
  app.use("/api/setting/agentDeploy/agentSetKey", route103);
  app.use("/api/setting/agentDeploy/deployAgentModel", route104);
  app.use("/api/setting/agentDeploy/getAgentDeploy", route105);
  app.use("/api/setting/dbConfig/clearData", route106);
  app.use("/api/setting/dev/getSwitchAiDevTool", route107);
  app.use("/api/setting/dev/updateSwitchAiDevTool", route108);
  app.use("/api/setting/fileManagement/openFolder", route109);
  app.use("/api/setting/getTextModel", route110);
  app.use("/api/setting/loginConfig/getUser", route111);
  app.use("/api/setting/loginConfig/updateUserPwd", route112);
  app.use("/api/setting/memoryConfig/delAllMemory", route113);
  app.use("/api/setting/memoryConfig/getMemory", route114);
  app.use("/api/setting/memoryConfig/sureMemory", route115);
  app.use("/api/setting/promptManage/getPrompt", route116);
  app.use("/api/setting/promptManage/updatePrompt", route117);
  app.use("/api/setting/skillManagement/getSkillContent", route118);
  app.use("/api/setting/skillManagement/getSkillList", route119);
  app.use("/api/setting/skillManagement/saveSkillContent", route120);
  app.use("/api/setting/vendorConfig/addVendor", route121);
  app.use("/api/setting/vendorConfig/deleteVendor", route122);
  app.use("/api/setting/vendorConfig/enableVendor", route123);
  app.use("/api/setting/vendorConfig/getCodeByLink", route124);
  app.use("/api/setting/vendorConfig/getVendorList", route125);
  app.use("/api/setting/vendorConfig/modelTest", route126);
  app.use("/api/setting/vendorConfig/updateCode", route127);
  app.use("/api/setting/vendorConfig/updateVendor", route128);
  app.use("/api/task/getProject", route129);
  app.use("/api/task/getTaskApi", route130);
  app.use("/api/task/getTaskCategories", route131);
  app.use("/api/task/taskDetails", route132);
  app.use("/api/test/test", route133);
}
